In [ ]:
#1. Write a program to reverse a string. Using function and loops 

In [76]:
def reverse(r): # defining function and argument
  a=""          #creating empty string
  for i in r:   #for loop
      a=i+a     #operation
      print(a)
  return a

In [77]:
reverse("kanmani")

k
ak
nak
mnak
amnak
namnak
inamnak


'inamnak'

In [12]:
#2.Write a program to check if a string is a palindrome.

In [13]:
def palindrome(str):
    if str == str[::-1]:
        print("Palindrome")
    else:
        print("not a palindrome")
   


palindrome()

In [14]:
palindrome("madam")

Palindrome


In [18]:
def fibo(n):
  if n == 1:
     print(0)
     return
  f=[0,1]
  for i in range(2,n):
    t=f[-1]+f[-2]
    f.append(t)
  print(f)


In [21]:
fibo(3)

[0, 1, 1]


In [ ]:
#4.Write a program to find all prime numbers up to n.

In [1]:
def prime(x):
    for i in range(0,x+1):  # to find the values from 0 to 7 x+1 is given 
        if i>1:
           for j in range(2,i):
               if(i%j)==0:
                  break
           else:
              print(i)
            

In [3]:
prime(5)

2
3
5


In [ ]:
#5.Write a program to remove duplicates from a list. Without set data structure


In [4]:
def list(d):
    e=[]
    for i in d:
        if i not in e:
            e.append(i)
    return e  

In [5]:
list([1, 2.0, 2.0, 3, 4, 5 , 6 ])

[1, 2.0, 3, 4, 5, 6]

In [3]:
#6.Create a program to find the second largest number in a list

In [11]:
def large(s):
    r=list(set(s))
    r.sort(reverse=True)
    return r[1]


In [13]:
large([34,45,2,67,2,45,99,67,87])

87

In [ ]:
#.Write a program to read and write to files with error handling.


In [75]:
def handle():
    try:
      with open('assessment.txt','w') as file:
          content = f1.write("good morning")
          print(content)
          f1.close()  
      f2 = open('assessment.txt','r')
      f2.read()
    except:
        print(f"Error:The file  does not exist.")
        return

In [74]:
handle()

Error:The file  does not exist.


In [51]:
#.Create a 3D NumPy array of shape (2, 3, 4). Convert it into a 2D array and then flatten it into a 1D array.

In [52]:
import numpy as np

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:
d3=np.array([[[2,1,4,5],[2,3,4,7],[3,4,9,3]],[[5,6,7,2],[5,7,4,2],[8,9,6,4]]]) #created 3D

In [19]:
d3

array([[[2, 1, 4, 5],
        [2, 3, 4, 7],
        [3, 4, 9, 3]],

       [[5, 6, 7, 2],
        [5, 7, 4, 2],
        [8, 9, 6, 4]]])

In [21]:
d3.ndim

3

In [22]:
d3.shape

(2, 3, 4)

In [32]:
d2 = d3.reshape(6,4)  #changed to 2 D

In [33]:
d2

array([[2, 1, 4, 5],
       [2, 3, 4, 7],
       [3, 4, 9, 3],
       [5, 6, 7, 2],
       [5, 7, 4, 2],
       [8, 9, 6, 4]])

In [34]:
d2.shape

(6, 4)

In [26]:
d2.ndim

2

In [35]:
d1=d2.flatten()  #flattened

In [36]:
d1

array([2, 1, 4, 5, 2, 3, 4, 7, 3, 4, 9, 3, 5, 6, 7, 2, 5, 7, 4, 2, 8, 9,
       6, 4])

In [ ]:
#10.Create two 2D NumPy arrays (3×2 and 2×3) and perform matrix multiplication using np.dot().


In [37]:
f1=np.array([[2,3,4],[6,7,8]]) #2cross3

In [38]:
f1

array([[2, 3, 4],
       [6, 7, 8]])

In [39]:
f1.ndim

2

In [42]:
f2=np.array([[5,6],[2,6],[4,9]]) #3cross2
            

In [43]:
f2


array([[5, 6],
       [2, 6],
       [4, 9]])

In [44]:
f2.ndim

2

In [45]:
f=np.dot(f1,f2) #multiplication

In [46]:
f

array([[ 32,  66],
       [ 76, 150]])