In [ ]:
#numpy pandas

In [1]:
import numpy as np

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.7 MB 11.5 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.7 MB 18.1 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.7 MB 21.6 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 18.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
#create
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
arr.shape

(3,)

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int64')

In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
b.shape

(2, 3)

In [12]:
b.ndim

2

In [13]:
b.dtype

dtype('int64')

In [14]:
c.dtype

dtype('int64')

In [15]:
c.ndim

2

In [16]:
a3 = np.array([
 [[1, 2], [3, 4]],
 [[5, 6], [7, 8]]
])

In [17]:
a3.ndim #finding dimension

3

In [18]:
a3.shape #shape

(2, 2, 2)

In [19]:
a3.dtype  #integer

dtype('int64')

In [20]:
z=np.zeros((2,3))

In [21]:
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
r=np.ones((2,3))

In [25]:
r

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
d=np.arange(0,10,2) 

In [27]:
d

array([0, 2, 4, 6, 8])

In [28]:
t=np.arange(0,100,5)

In [29]:
t

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [30]:
f=np.linspace(5,50,5)

In [31]:
f

array([ 5.  , 16.25, 27.5 , 38.75, 50.  ])

In [32]:
i=np.eye(3)

In [33]:
i


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.zeros((2, 3)) # 2x3 array of zeros
#np.ones((2, 2)) # 2x2 array of ones
#np.eye(3) # 3x3 identity matrix
#np.arange(0, 10, 2) # [0, 2, 4, 6, 8]
#np.linspace(0, 1, 5) # 5 values between 0 and 1

In [34]:
s=np.array([1,2,3,4])
s

array([1, 2, 3, 4])

In [35]:
r=np.array([6,7,8,9])
r

array([6, 7, 8, 9])

In [ ]:
#element wise operation

In [36]:
s+r

array([ 7,  9, 11, 13])

In [37]:
s*r

array([ 6, 14, 24, 36])

In [40]:
s**2

array([ 1,  4,  9, 16])

In [42]:
y=np.dot(s,r)

In [43]:
y

np.int64(80)

In [45]:
k=np.array([5,6,7],dtype=float)

In [ ]:
Create two d

In [48]:
c=np.array([[2,3,6],[4,5,9]])

In [49]:
d=np.array([[8,3,4],[7,11,1]])

In [50]:
c


array([[2, 3, 6],
       [4, 5, 9]])

In [51]:
d

array([[ 8,  3,  4],
       [ 7, 11,  1]])

In [52]:
c+d

array([[10,  6, 10],
       [11, 16, 10]])

In [53]:
c*d

array([[16,  9, 24],
       [28, 55,  9]])

In [54]:
c**2

array([[ 4,  9, 36],
       [16, 25, 81]])

In [55]:
z=np.dot(c,d) #since there no proper dimension formed it will throw error

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
d=d.reshape(3,2)

In [57]:
z=np.dot(c,d)

In [58]:
z

array([[ 94,  33],
       [151,  56]])

In [61]:
w=np.mean(s)

In [62]:
w

np.float64(2.5)

In [63]:
f=np.median(s) #no mode

In [64]:
f

np.float64(2.5)

In [65]:
u=np.std(s)

In [66]:
u

np.float64(1.118033988749895)

In [67]:
q=np.sin(s)

In [68]:
q

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [70]:
np.unique(s)

array([1, 2, 3, 4])

In [71]:
np.sort(s)

array([1, 2, 3, 4])

In [73]:
np.concatenate([s,r])

array([1, 2, 3, 4, 6, 7, 8, 9])